-- try to solve again
WITH U AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN "2021-01-01" AND "2021-12-31"
)
SELECT
    DATE_FORMAT(S.SALES_DATE, "%Y") AS YEAR,
    DATE_FORMAT(S.SALES_DATE, "%m") AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM U), 1) AS PURCHASED_RATE
FROM ONLINE_SALE AS S
    JOIN U
        ON S.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC