-- Try to solve again
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * (1 - D.DISCOUNT_RATE * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = "30일 이상") AS D
        ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV") 
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE "2022-11-01" <= END_DATE AND START_DATE <= "2022-11-30"
    )   
GROUP BY C.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC