SELECT E1.ID, COUNT(CASE WHEN E2.PARENT_ID IS NOT NULL THEN 1 END) AS CHILD_COUNT
    FROM ECOLI_DATA E1
        LEFT OUTER JOIN ECOLI_DATA E2
            ON E1.ID = E2.PARENT_ID
    GROUP BY E1.ID
    ORDER BY E1.ID ASC;